### ISSUE TITLE
Binnaries for PHP 5.3x

### ISSUE THREAD

**Issue by astral2k5** [kenjiuno/php-wfio#17]
Hi @kenjiuno,

Thanks for your project. I'm trying to use your extension on PHP 5.3.x but is not working.

Is it possible to make a release for 5.3.x version VC6/VC9 ?
Unfortunately I need to use 5.3, can't update to 5.4 on my project.

Thanks!

**Comment by kenjiuno** [comment]
Hi, it may take some days... I have lost local build systems.

**Comment by kenjiuno** [comment]
Ok finally I have built and packed `wfio-0.4-php5.3.7z` (VC9)
Try https://github.com/kenjiuno/php-wfio/releases/tag/v0.4

**Comment by astral2k5** [comment]
Thanks!
