### ISSUE TITLE
filesize() support

### ISSUE THREAD

**Issue by aky-redwoodtech** [kenjiuno/php-wfio#18]
Hi,

For business reasons we cannot upgrade to PHP 7 and are still using PHP 5.6.30. Can this plugin do filesize() and if not do you know any other methods for getting the size of a file with Japanese characters in its name?

Many thanks in advance for the response.

**Comment by kenjiuno** [comment]
Hi. `filesize` should work on PHP 5.x with PHP stream wrapper.

```php
<?php
echo filesize('wfio://C:\A\😁.tif');
?>
```

```bat
C:\php5>php.exe C:\A\A.php
7980
```

```bat
Active code page: 65001

C:\php5>cd \A

C:\A>dir 😁.tif
 Volume in drive C has no label.
 Volume Serial Number is CA6D-4F59

 Directory of C:\A

2019/09/26  17:42             7,980 😁.tif
               1 File(s)          7,980 bytes
               0 Dir(s)  52,601,081,856 bytes free

C:\A>
```

However php's integer is limited to 32-bit signed integer around -2GB to +2GB
