### ISSUE TITLE
ZipArchive support

### ISSUE THREAD

**Issue by garethellis36** [kenjiuno/php-wfio#2]
Thanks for a great extension - it's solved some issues I've been having for a while.

@kenjiuno Is it possible to have the extension support ZipArchive? It would be great to be able to do $zip->addFile('wsio://source', 'wsio://dest');

**Comment by garethellis36** [comment]
Any news on this? :-)

**Comment by kenjiuno** [comment]
Sorry, there is no progress... I'll need more time.

**Comment by kenjiuno** [comment]
Hi.

Sorry, unfortunately, ZipFile doesn't support stream wrappers.

Please consider to use `PharData` class in this case. It supports stream wrappers as a file input. http://php.net/manual/en/phardata.addfile.php

Example:
```
<?php

$zip = new PharData($filename = "./test.zip");
$zip->addFile("wfio://install.txt", "install.txt");

?>
```

**Comment by garethellis36** [comment]
Thanks for looking into this. I'll check out `PharData`!
