### ISSUE TITLE
Relative paths not working if current working directory contains nonascii characters

### ISSUE THREAD

**Issue by jrohel** [kenjiuno/php-wfio#7]
Relative paths not working if current working directory contains nonascii characters.

Probably problem is in file "php_wfio.c" in function "wfio_realpathw()".
We get "workdir" from "VCWD_GETCWD" function and then use "MultiByteToWideChar" with CP_UTF8. Probably use CP_ACP instead of CP_UTF8 is solution.

In "PHP_FUNCTION(wfio_getcwd8)" is also used "VCWD_GETCWD" (path saved to "buffer") but at this function is  "MultiByteToWideChar" used with CP_ACP. This is probably OK.

I can't test this because I don't have Visual Studio C++ and SDK installed.

**Comment by kenjiuno** [comment]
Hi.

Thanks for the detail report! I'll check the problem you have discovered!

**Comment by kenjiuno** [comment]
Hi.

Thanks, the problem is fixed. Please try latest one!
https://github.com/kenjiuno/php-wfio/releases/tag/v0.3

**Comment by jrohel** [comment]
Thanks.
But I have strange problems. (Result with new dll is the same.)

I done test (script copy.php works, only in nonascii directory or only if
is called with fullpath without backslash behind colon.) I do not know
where problem is now.

Test:
C:\php>type c:\s\copy.php
<?php
        $fp = fopen('src.txt', 'w');
        fwrite($fp, 'Some text');
        fclose($fp);
        copy('wfio://src.txt', 'wfio://dst.txt');
?>

C:\php>copy c:\s\copy.php c:\š\copy.php
        1 file(s) copied.

C:\php>php-cgi.exe c:\s\copy.php
X-Powered-By: PHP/5.6.7
Content-type: text/html; charset=UTF-8

C:\php>php-cgi.exe c:\š\copy.php
X-Powered-By: PHP/5.6.7
Content-type: text/html; charset=UTF-8

<br />
<b>Warning</b>:  copy(): It is not safe to rely on the system's timezone
setting
s. You are *required* to use the date.timezone setting or the
date_default_timez
one_set() function. In case you used any of those methods and you are still
gett
ing this warning, you most likely misspelled the timezone identifier. We
selecte
d the timezone 'UTC' for now, but please set date.timezone to select your
timezo
ne. in <b>C:\Ü\copy.php</b> on line <b>5</b><br />
<br />
<b>Warning</b>:  copy(wfio://src.txt): failed to open stream: operation
failed i
n <b>C:\Ü\copy.php</b> on line <b>5</b><br />

C:\php>php-cgi.exe c:š\copy.php
X-Powered-By: PHP/5.6.7
Content-type: text/html; charset=UTF-8

C:\php>
Dne 22.3.2015 13:18 "kenjiuno" <notifications@github.com> napsal(a):

**Comment by kenjiuno** [comment]
Hi.

Thanks for testing it!

Please let me know: `š` is an unicode character that your Windows cannot convert it in CP_ACP?

**Comment by jrohel** [comment]
Hi,

š is Czech character.. It is defined in many codetables iso8859-2, cp1250,
cp852, ...
I'm not sure what happens. May be problem is not at wfio. I try another
test:

C:\phpŠščřžýáíé>type pwp.php
<?php
        system("pwd");
        echo getcwd()."\r\n";
        echo iconv("cp1250", "cp852", getcwd())."\r\n";
        echo iconv("", "cp852", getcwd())."\r\n";
?>

C:\phpŠščřžýáíé>pwd
/c/phpŠščřžýáíé

C:\phpŠščřžýáíé>php-cgi.exe pwp.php
X-Powered-By: PHP/5.6.7
Content-type: text/html; charset=UTF-8

/c/phpŐÜŔ°×řßÝÚ
C:\phpŐÜŔ°×řßÝÚ
C:\phpŠščřžýáíé
C:\phpŠščřžýáíé

C:\phpŠščřžýáíé>


What does it mean?
"pwd" command returns cp852 encoding in command line and cp1250 encoding in
php system("pwd")?
Php "getcwd()" returns cp1250 encoding. And cp852 is in console?
I tried change php.ini (default_charset, internal_encoding, etc.). Output
was the same.
Many questions now. I'm thinking about what I'm doing wrong.




2015-03-24 1:49 GMT+01:00 kenjiuno <notifications@github.com>:
