### ISSUE TITLE
is_dir, is_file, file_exists support and scandir() exception

### ISSUE THREAD

**Issue by ids93216** [kenjiuno/php-wfio#8]
Hi, thanks for great extension.
I'm running on PHP5.6.16 NTS x64 FastCGI, Nginx 1.9.5, Windows Server 2012 zh_TW now.

I use is_dir(), is_file() and file_exists() these function with wfio://, but it always return false.
And use scandir('wfio://') to access wrong path (not exist or no permission) will cause PHP-CGI crash.

![default](https://cloud.githubusercontent.com/assets/4828920/11685039/09d637ac-9eb1-11e5-892a-6130799896b3.png)

Is there any way to fix these problem?

Then hope PHP7 support will release soon! Thanaks!

**Comment by kenjiuno** [comment]
Hi.

What's about content of `$path`, is it path encoded in UTF-8?

**Comment by ids93216** [comment]
Oops.. I knew why that I always got false returning...

It seems can't be end with a "/" when detecting a directory.
Is there a bug?

Ex. "wfio://D:/abc/" return false, but "wfio://D:/abc" will return true.
Encoding is all UTF-8.

scandir() if target not found, PHP-CGI will crash, whether any encoding.

**Comment by kenjiuno** [comment]
Ok, I'll check about it. Thanks for reporting!

**Comment by kenjiuno** [comment]
This'll be fixed in b5243e727ee39744b2b42018796e098eea4ac3ab
> Ex. "wfio://D:/abc/" return false, but "wfio://D:/abc" will return true.

This will be fixed in ec15387b1dc2540dd0ad0d9ef8657c27fe5c4a14
> will cause PHP-CGI crash.

I have some tasks to do before next release.
- check `scandir() if target not found, PHP-CGI will crash, whether any encoding.`
- tests on PHP 7.

**Comment by kenjiuno** [comment]
Ok, this'll be fixed 1082bb0d3a1f02b65d8a46975238b595b5977448
> scandir() if target not found, PHP-CGI will crash, whether any encoding.

php_wfio will work on PHP7, since my tests pass.

Please wait while building 14 variants of php_wfio.dll.

**Comment by kenjiuno** [comment]
Thanks, the new release is ready:
https://github.com/kenjiuno/php-wfio/releases/tag/v0.4

**Comment by ids93216** [comment]
Wow, you works so fast!

It's works well with PHP 7.0.0 now. Thanks again for great extension!
